# Generated by Django 5.2.3 on 2025-07-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Student', max_length=100)),
                ('gender', models.CharField(default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('index', models.IntegerField()),
                ('question_type', models.CharField(choices=[('knowledge', 'knowledge'), ('preference', 'preference')], max_length=20)),
                ('selected_option_id', models.CharField(blank=True, max_length=10, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.player')),
            ],
            options={
                'unique_together': {('player', 'question_id')},
            },
        ),
    ]
