# Generated by Django 5.2.3 on 2025-07-12 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_points_earned_surveyresponse_ai_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='ai_score',
            new_name='ai_points',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='computing_score',
            new_name='computing_points',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='cybersecurity_score',
            new_name='cybersecurity_points',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='score',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='correctly_answered',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='selected_options_from_one_to_five',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='selected_options_rest_questions',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='skipped',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='recommendation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=100, null=True)),
                ('question_id', models.IntegerField()),
                ('question_type', models.CharField(choices=[('knowledge', 'Knowledge'), ('preference', 'Preference')], max_length=20)),
                ('selected_option_id', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('AI', 'AI'), ('Computing', 'Computing'), ('Cybersecurity', 'Cybersecurity')], max_length=50)),
                ('points_earned', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('player_id', 'question_id')},
            },
        ),
    ]
