# Generated by Django 5.2.3 on 2025-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_id_surveyresponse_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecord',
            name='index',
            field=models.IntegerField(),
        ),
    ]
